dist: bionic
sudo: required
language: python

notifications:
  email: false

python:
- "3.6"
- "3.7"
- "3.8"

before_install:
- sudo apt-get install -y libopenjp2-7

install:
- if [ $TRAVIS_PYTHON_VERSION == '3.7' ]; then
    pip install -e .[DEV] --upgrade ;
  else
    pip install .[DEV] --upgrade ;
  fi

script:
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pylint sentinelhub ; fi
- >
  if [[ ("$TRAVIS_PULL_REQUEST" != "false") || ( $TRAVIS_PYTHON_VERSION != '3.7') ]] ;
  then pytest --cov \
    --ignore tests/test_ogc.py \
    --ignore tests/test_sentinelhub_batch.py \
    --ignore tests/test_sentinelhub_client.py \
    --ignore tests/test_session.py \
    --ignore tests/test_fis.py \
    --ignore tests/test_data_request.py \
    --ignore tests/test_aws.py \
    --ignore tests/test_aws_safe.py \
    --ignore tests/test_commands.py ;
  else pytest --cov ;
  fi

after_success:
- if [ $TRAVIS_PYTHON_VERSION == '3.7' ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then codecov; fi
